- project:
    check: &jobs
      jobs:
        - cabal-test:
            vars:
              ghc_version: 8.8
              cabal_target: "--write-ghc-environment-files=always"
            nodeset:
              nodes:
                - name: container
                  label: zuul-worker-haskell
            required-projects:
              - software-factory/gerrit-haskell
              - software-factory/podman-haskell
              - software-factory/zuul-haskell
              - software-factory/pypi-haskell
        - hlint:
            nodeset:
              nodes:
                - name: container
                  label: zuul-worker-haskell
    gate: *jobs
